#!/bin/sh -e

ACTION=${2}

if [ "${ACTION}" != "connectivity-change" ] || \
   [ "${CONNECTIVITY_STATE}" = "NONE" ]; then
    exit 0
fi

/bin/systemd-run --no-block --on-active=2m --unit=kolibri-update-channels.service

exit 0
