#!/bin/bash

if [ "$EUID" != "0" ]; then
    echo "$0: This script requires superuser privileges" >&2
    exit 1
fi

run_kolibri() {
    user="$1"
    shift
    kolibri_home="$1"
    shift
    command="flatpak run --command=kolibri org.learningequality.Kolibri $@"

    KOLIBRI_HOME="$kolibri_home" su -c "$command" "$user_name"
}

kolibri_home_relative_path=".var/app/org.learningequality.Kolibri/data/kolibri"

cat /etc/passwd | while read -r user_line; do
    user_name=$(echo $user_line | cut -d : -f 1)
    user_home=$(echo $user_line | cut -d : -f 6)
    user_kolibri_home="$user_home/$kolibri_home_relative_path"

    if [ -f "$user_kolibri_home/db.sqlite3" ]; then
        echo "Updating '$user_name' Kolibri channels"

        channels=$(\
            run_kolibri "$user_name" "$user_kolibri_home" manage listchannels 2> /dev/null \
            | tail -n +3 \
            | tr -s " " \
            | cut -d " " -f 2 \
        )

        for channel in $channels; do
            run_kolibri "$user_name" "$user_kolibri_home" manage importchannel network "$channel"
            run_kolibri "$user_name" "$user_kolibri_home" manage importcontent network "$channel"
        done
    else
        echo "User '$user_name' does not use Kolibri, skipping..."
    fi
done
