#!/bin/bash

if [ "$EUID" != "0" ]; then
    echo "$0: This script requires superuser privileges" >&2
    exit 1
fi

# Make sure stamp file is at least 6 hours old or missing
stamp_file="/var/lock/kolibri-update-channels.service.stamp"
if [ -f "$stamp_file" -a -z "$(find $stamp_file -mmin +360 2> /dev/null)" ]; then
    echo "$0: Stamp file is new enough, skipping..." >&2
    exit 0
fi
touch "$stamp_file"

run_kolibri() {
    user="$1"
    shift
    kolibri_home="$1"
    shift
    command="flatpak run --command=kolibri org.learningequality.Kolibri $@"

    KOLIBRI_HOME="$kolibri_home" su -c "$command" "$user_name"
}

run_kolibri_import() {
    run_kolibri "$user_name" "$user_kolibri_home" manage $@ network \
        --baseurl "$KOLIBRI_UPDATE_CHANNELS_BASEURL" "$channel"
}

show_kolibri_notification() {
    DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$1/bus" \
        su -c "notify-send -i org.learningequality.Kolibri \"Kolibri automatic updates\" \"$2\"" "$1"
}

kolibri_home_relative_path=".var/app/org.learningequality.Kolibri/data/kolibri"

cat /etc/passwd | while read -r user_line; do
    user_name=$(echo $user_line | cut -d : -f 1)
    user_id=$(echo $user_line | cut -d : -f 3)
    user_home=$(echo $user_line | cut -d : -f 6)
    user_kolibri_home="$user_home/$kolibri_home_relative_path"

    if [ -f "$user_kolibri_home/db.sqlite3" ]; then
        echo "Updating '$user_name' Kolibri channels"
        show_kolibri_notification "$user_name" "Updating Kolibri channels"

        channels=$(\
            run_kolibri "$user_name" "$user_kolibri_home" manage listchannels 2> /dev/null \
            | tail -n +3 \
            | tr -s " " \
            | cut -d " " -f 2 \
        )

        for channel in $channels; do
            run_kolibri_import importchannel
            run_kolibri_import importcontent
        done

        show_kolibri_notification "$user_name" "Kolibri channels update has finished"
    else
        echo "User '$user_name' does not use Kolibri, skipping..."
    fi
done

exit 0
